-- 코드를 입력하세요
SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, car_id, COUNT(*) as records FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE car_id in (
SELECT car_id FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE start_date BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
GROUP BY car_id
HAVING COUNT(car_id) >= 5)
AND start_date between TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
GROUP BY EXTRACT(MONTH FROM START_DATE), car_id
ORDER BY EXTRACT(MONTH FROM START_DATE), car_id desc