SELECT A.FLAVOR FROM
(SELECT TMP.FLAVOR, (TMP.total_order + J.total_order) AS total_order
FROM 
(SELECT FH.FLAVOR, FH.TOTAL_ORDER
FROM FIRST_HALF FH
INNER JOIN JULY J
ON J.SHIPMENT_ID = FH.SHIPMENT_ID) TMP
INNER JOIN (
SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR) J
ON TMP.FLAVOR = J.FLAVOR
ORDER BY total_order DESC) A
WHERE ROWNUM < 4


