-- 코드를 입력하세요
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN
(SELECT CATEGORY, MAX(PRICE) AS PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY = '식용유' 
      OR CATEGORY = '과자' 
      OR CATEGORY = '국' 
      OR CATEGORY = '김치'
GROUP BY CATEGORY )
ORDER BY PRICE DESC