-- 코드를 입력하세요
SELECT ORDER_ID, PRODUCT_ID, TO_CHAR(OUT_DATE,'YYYY-MM-DD'),
CASE WHEN TO_CHAR(OUT_DATE, 'MM-DD') < '05-02' THEN '출고완료'
     WHEN TO_CHAR(OUT_DATE, 'MM-DD') >= '05-02' THEN '출고대기'
     ELSE '출고미정'
     END AS h
FROM FOOD_ORDER
WHERE 1=1
ORDER BY ORDER_ID ASC