-- 코드를 입력하세요
SELECT S.PRODUCT_ID, S.PRODUCT_NAME, SUM(S.PRICE * S.AMOUNT) AS TOTAL_SALES
FROM 
(SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRICE, FO.AMOUNT
FROM FOOD_PRODUCT FP
INNER JOIN FOOD_ORDER FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE TO_CHAR(FO.PRODUCE_DATE, 'YYYY-MM') = '2022-05') S
GROUP BY S.PRODUCT_ID, S.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, S.PRODUCT_ID ASC